routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();



Route::middleware('auth')->group(function () {
    Route::get('/follow/{id}', 'UserController@follow')->name('follow');
    Route::get('/', 'HomeController@index')->name('home')->name('home');
    Route::get('/profile/{id}', 'HomeController@viewProfile')->name('profile'); //profile ini ada atau engga ya? profile dan user apakah sama?
    Route::get('/post/create', 'PostController@create');
    Route::get('/mypost/', 'PostController@index');
    Route::get('/post/{id}', 'PostController@show');
    Route::post('/post/', 'PostController@store');
    Route::get('/mypost/{id}/edit', 'PostController@edit');
    Route::put('/mypost/{id}/', 'PostController@update');
    Route::delete('/mypost/{id}/', 'PostController@destroy');
    Route::post('/post/{id}/comment', 'PostCommentController@store');
    Route::post('/post/{id}/like', 'LikePostController@like');
    Route::delete('/post/{id}/like', 'LikePostController@dislike');
    Route::post('/comment/{id}/like', 'LikeCommentController@like');
    Route::delete('/comment/{id}/like', 'LikeCommentController@dislike');
    Route::post('/comment/{id}/comment', 'ReplyCommentController@store');
    Route::resource('user', 'UserController');});

resources/views/home.blade.php
@extends('layouts.master')
@section('judul-card', 'Timeline')

@section('content')
<div class="container">
    <div class="row justify-content-center mb-2">
        <div class="col-md-6">
            @forelse ($posts as $post)
            <div class="card bg-light d-flex flex-fill mb-2">
                <div class="card-header" style="margin: initial !important;">
                    <a href="{{ route('profile', $post->user_id) }}">{{$post->user->name}}</a>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">{{$post->tulisan}}</div>
                    </div>
                    @if ($post->gambar != "")
                    <div class="row">
                        <div class="col-12">
                            <img src="{{ asset('img/posts/'.$post->gambar) }}" alt="posts"
                                style="width: 100%; height:auto;">
                        </div>
                    </div>
                    @endif
                    <div class="row">
                        <div class="col-6">
                           <form action="/post/{{$post->id}}/like" method="post" id="like">
                            @csrf
                            @forelse ($post->likepost as $like)
                            @method('DELETE')
                            <?php $class = "fas fa-heart";
                                  $liked = "Unlike";
                            ?>
                            @empty
                            <?php $class = "far fa-heart";
                                  $liked = "Like";
                            ?>
                            @endforelse
                            <button type="submit" class="btn btn-link"><i class="{{$class}}"></i> {{$post->likepost->count()}} {{$liked}}</button>
                            <a href="/post/{{$post->id}}"> <i class="far fa-comment"></i> {{$post->comment->count()}}  Comment</a>

                        </form>
                            {{-- <i class="fas fa-heart"></i> Liked --}}
                        </div>
                        <div class="col-6 text-right">
                            <span> {{ \Carbon\Carbon::parse($post->created_at)->diffForHumans() }} </span>
                        </div>
                    </div>
                </div>
                </a>
                
                <br>
            </div>
            @empty
            <center>No data</center>
            @endforelse
        </div>
    </div>
</div>
@endsection

resources/views/profile.blade.php
@extends('layouts.master')
@push('style')
<link href="{{ asset('css/custom.css') }}" rel="stylesheet">
@endpush
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card">
                <img class="profile-image" src="{{ asset('img/default-avatar.png') }}" alt="Card image" />
                <div class="card-body">
                    <h4 class="card-title text-center">{{ $profile->name }}</h4>
                    <div class="card-title text-center mb-2 mt-2">
                        @if (Auth::user()->id == $profile->id)
                        <a class="btn btn-info btn-sm text-white text-center"
                            href="{{ route('user.edit', $profile->id) }}">Edit
                            Profile</a>
                        @else
                        <a class="btn btn-primary btn-sm text-white text-center"
                            onclick="follow({{ $profile->id }}, this)">
                            {{ Auth::user()->following->contains($profile->id) ? 'Unfollow' : 'Follow' }}
                        </a>
                        @endif

                        <script>
                            function follow(id, el) {
                                    fetch('/follow/' + id)
                                    .then(respense => respense.json())
                                    .then(data => {
                                        el.innerText = (data.status == 'follow') ? 'Unfollow' : 'Follow'
                                    })
                                }
                        </script>
                    </div>
                    <div class="row">
                        <div class="col-4 text-center">{{ $postCount ? $postCount : 0 }} Postingan
                        </div>
                        <div class="col-4 text-center">{{ $profile->mengikuti ? $profile->mengikuti : 0 }} Mengikuti
                        </div>
                        <div class="col-4 text-center">{{ $profile->pengikut ? $profile->pengikut : 0 }} Pengikut</div>
                    </div>
                    <p class="text-center mt-2">{{ $profile->biodata }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')

@endpush

resources/views/setting.blade.php
@extends('layouts.master')
@push('style')
<link href="{{ asset('css/custom.css') }}" rel="stylesheet">
@endpush
@section('content')
<div class="container">
    <div class="row">
        <div class="col-4">
            <div class="card">
                <img class="profile-image" style="border: 1px solid #dfdfdf;"
                    src="{{ $user->avatar ? $user->avatar : 'img/default-avatar.png' }}" alt="Card image" />
                <div class="card-body">
                    <h4 class="card-title text-center">{{ $user->name }}</h4>
                    <div class="row">
                        <div class="col-6 text-center">{{ $user->mengikuti ? $user->mengikuti : 0 }} Mengikuti</div>
                        <div class="col-6 text-center">{{ $user->pengikut ? $user->mengikuti : 0 }} Pengikut</div>
                    </div>
                    <p class="text-center mt-2">{{ $user->biodata }}</p>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card">
                <div class="card-header">User Profile</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('user.update', $user->id) }}">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input id="name" type="text" class="form-control form-control-sm " name="name"
                                value="{{ isset($user->name) ? $user->name : '' }}" autocomplete="name" autofocus>
                        </div>

                        <div class="form-group">
                            <label for="email">{{ __('E-Mail Address') }}</label>
                            <input class="form-control form-control-sm"
                                value="{{ isset($user->email) ? $user->email : '' }}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="biodata">{{ __('Biodata') }}</label>
                            <textarea class="form-control form-control-sm"
                                placeholder="{{ isset($user->biodata) ? $user->biodata : '' }}" name="biodata"
                                rows="3"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="password">{{ __('Password') }}</label>
                            <input id="password" type="password" class="form-control form-control-sm" name="password"
                                autocomplete="new-password">
                        </div>

                        <div class="form-group">
                            <label for="password-confirm">{{ __('Confirm Password') }}</label>
                            <input id="password-confirm" type="password" class="form-control form-control-sm"
                                name="password_confirmation" autocomplete="new-password">
                        </div>

                        <div class="form-group mb-0">
                            <button type="submit" class="btn btn-primary">
                                {{ __('Update') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection